#!/bin/python3
import argparse
import columnize

from num_tables import *


def parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("num", type=str, nargs="?")

    args = parser.parse_args()
        
    return args


def main():
    args = parser()

    n = args.num
    if args.num is not None:
        if "0x" in n:
            m = int(n[2:], 16)
            print(n, b(m), d(m))
        elif "0b" in args.num:
            m = int(n[2:], 2)
            print(n, h(m), d(m))
        elif args.num.isdigit():
            m = int(n)
            print(n, h(m), b(m))
        
    else:
        print(columnize.columnize([f"{n:3}:{n:08b}:{n:02X}" for n in range(0xFF+1)], displaywidth=360))
    

if __name__ == "__main__":
    main()
