#!/bin/python3
import argparse
import columnize

from num_utils import *

def parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("num", type=str, nargs="*")

    args = parser.parse_args()
        
    return args


def handle_range_arg(arg):
    if ".." in arg:
        start, end = arg.split("..")
        start = num_conversion(start)
        end = num_conversion(end)
        return list(range(start, end))
    else:
        return arg

        
def main():
    args = parser()

    if len(args.num):
        for num in args.num:
            num = handle_range_arg(num)
            if isinstance(num, list):
                print(columnize.columnize([format_number(n) for n in num], displaywidth=160))
            else:
                print(format_conversion(num))
    else:
        print(columnize.columnize([f"{n:3}:{n:08b}:{n:02X}" for n in range(0xFF+1)]))
    

if __name__ == "__main__":
    main()
